import { Widget, WidgetType } from '../types/widget';
import { WIDGET_DEFAULTS } from '../constants';

export const snapToGrid = (value: number, gridSize: number, enabled: boolean): number => {
  return enabled ? Math.round(value / gridSize) * gridSize : value;
};

export const createWidget = (
  type: WidgetType,
  x: number,
  y: number,
  widgets: Widget[]
): Widget => {
  const widgetName = `${type}${widgets.filter(w => w.type === type).length + 1}`;

  const baseWidget: Partial<Widget> = {
    id: Date.now(),
    type,
    name: widgetName,
    x: Math.max(0, x - (WIDGET_DEFAULTS[type]?.width || 80) / 2),
    y: Math.max(0, y - 15),
    width: WIDGET_DEFAULTS[type]?.width || 80,
    height: WIDGET_DEFAULTS[type]?.height || 30,
    text: widgetName,
    bgColor: type === 'frame' ? '#f9fafb' : type === 'button' ? '#3b82f6' : '#f0f0f0',
    textColor: type === 'button' ? '#ffffff' : '#000000',
    fontSize: 12,
    fontWeight: 'normal',
    fontStyle: 'normal',
    textAlign: 'left',
    borderWidth: type === 'frame' ? 2 : 0,
    borderColor: '#d1d5db',
    zIndex: widgets.length,
    eventCode: '',
  };

  if (type === 'textbox' || type === 'textarea') {
    const defaults = WIDGET_DEFAULTS[type] as { width: number; height: number; placeholder: string; maxLength: number };
    return {
      ...baseWidget,
      placeholder: defaults.placeholder,
      maxLength: defaults.maxLength,
    } as Widget;
  }

  if (type === 'checkbox') {
    const defaults = WIDGET_DEFAULTS[type] as { width: number; height: number; checked: boolean };
    return {
      ...baseWidget,
      checked: defaults.checked,
    } as Widget;
  }

  if (type === 'radio') {
    const defaults = WIDGET_DEFAULTS[type] as { width: number; height: number; checked: boolean; group: string };
    return {
      ...baseWidget,
      checked: defaults.checked,
      group: defaults.group,
    } as Widget;
  }

  if (type === 'slider') {
    const defaults = WIDGET_DEFAULTS[type] as { width: number; height: number; min: number; max: number; value: number; step: number };
    return {
      ...baseWidget,
      min: defaults.min,
      max: defaults.max,
      value: defaults.value,
      step: defaults.step,
    } as Widget;
  }

  if (type === 'progressbar') {
    const defaults = WIDGET_DEFAULTS[type] as { width: number; height: number; min: number; max: number; value: number };
    return {
      ...baseWidget,
      min: defaults.min,
      max: defaults.max,
      value: defaults.value,
    } as Widget;
  }

  if (type === 'listbox') {
    const defaults = WIDGET_DEFAULTS[type] as { width: number; height: number; items: string[] };
    return {
      ...baseWidget,
      items: defaults.items,
    } as Widget;
  }

  if (type === 'combobox') {
    const defaults = WIDGET_DEFAULTS[type] as { width: number; height: number; items: string[]; selectedIndex: number };
    return {
      ...baseWidget,
      items: defaults.items,
      selectedIndex: defaults.selectedIndex,
    } as Widget;
  }

  return baseWidget as Widget;
};

export const generatePythonCode = (
  formTitle: string,
  formSize: { width: number; height: number },
  widgets: Widget[]
): string => {
  let code = `import tkinter as tk\nfrom tkinter import ttk, messagebox\n\n`;
  code += `# Generated by Visual Python IDE\n\n`;
  code += `class ${formTitle.replace(/\s+/g, '')}:\n`;
  code += `    def __init__(self, root):\n`;
  code += `        self.root = root\n`;
  code += `        self.root.title("${formTitle}")\n`;
  code += `        self.root.geometry("${formSize.width}x${formSize.height}")\n`;
  code += `        self.root.resizable(False, False)\n`;
  code += `        self.widgets = {}  # 위젯 참조용 딕셔너리\n\n`;
  code += `        self.create_widgets()\n\n`;
  code += `    def msgBox(self, message, title="Message", type="info"):\n`;
  code += `        """VB-style MsgBox 함수"""\n`;
  code += `        if type == "info":\n`;
  code += `            messagebox.showinfo(title, message)\n`;
  code += `        elif type == "warning":\n`;
  code += `            messagebox.showwarning(title, message)\n`;
  code += `        elif type == "error":\n`;
  code += `            messagebox.showerror(title, message)\n`;
  code += `        elif type == "question":\n`;
  code += `            return messagebox.askyesno(title, message)\n\n`;
  code += `    def create_widgets(self):\n`;

  const sortedWidgets = [...widgets].sort((a, b) => (a.zIndex || 0) - (b.zIndex || 0));

  sortedWidgets.forEach((w) => {
    const varName = `self.widgets["${w.name}"]`;
    const fontStr = `("Arial", ${w.fontSize}, "${w.fontWeight} ${w.fontStyle}".strip())`;
    
    switch(w.type) {
      case 'label':
        code += `        ${varName} = tk.Label(self.root, text="${w.text}", bg="${w.bgColor}", fg="${w.textColor}", font=${fontStr}, anchor="${w.textAlign}")\n`;
        break;
      case 'button':
        code += `        ${varName} = tk.Button(self.root, text="${w.text}", bg="${w.bgColor}", fg="${w.textColor}", font=${fontStr}, command=self.on_${w.name}_click)\n`;
        break;
      case 'textbox':
        code += `        ${varName} = tk.Entry(self.root, bg="${w.bgColor}", fg="${w.textColor}", font=${fontStr})\n`;
        if (w.placeholder) {
          code += `        ${varName}.insert(0, "${w.placeholder}")\n`;
        }
        break;
      case 'textarea':
        code += `        ${varName} = tk.Text(self.root, bg="${w.bgColor}", fg="${w.textColor}", font=${fontStr})\n`;
        break;
      case 'checkbox':
        code += `        ${varName}_var = tk.BooleanVar(value=${w.checked || false})\n`;
        code += `        ${varName} = tk.Checkbutton(self.root, text="${w.text}", bg="${w.bgColor}", fg="${w.textColor}", font=${fontStr}, variable=${varName}_var)\n`;
        break;
      case 'radio':
        code += `        ${varName}_var = tk.StringVar(value="${w.checked ? w.text : ''}")\n`;
        code += `        ${varName} = tk.Radiobutton(self.root, text="${w.text}", bg="${w.bgColor}", fg="${w.textColor}", font=${fontStr}, variable=${varName}_var, value="${w.text}")\n`;
        break;
      case 'listbox':
        code += `        ${varName} = tk.Listbox(self.root, bg="${w.bgColor}", fg="${w.textColor}", font=${fontStr})\n`;
        if (w.items && w.items.length > 0) {
          w.items.forEach(item => {
            code += `        ${varName}.insert(tk.END, "${item}")\n`;
          });
        }
        break;
      case 'combobox':
        const items = w.items && w.items.length > 0 ? JSON.stringify(w.items) : '["Option 1", "Option 2", "Option 3"]';
        code += `        ${varName} = ttk.Combobox(self.root, values=${items}, font=${fontStr})\n`;
        if (w.selectedIndex !== undefined && w.items && w.items[w.selectedIndex]) {
          code += `        ${varName}.set("${w.items[w.selectedIndex]}")\n`;
        }
        break;
      case 'slider':
        code += `        ${varName} = tk.Scale(self.root, from_=${w.min || 0}, to=${w.max || 100}, orient=tk.HORIZONTAL, resolution=${w.step || 1})\n`;
        code += `        ${varName}.set(${w.value || 50})\n`;
        break;
      case 'progressbar':
        code += `        ${varName} = ttk.Progressbar(self.root, maximum=${w.max || 100}, value=${w.value || 0})\n`;
        break;
      case 'frame':
        code += `        ${varName} = tk.Frame(self.root, bg="${w.bgColor}", relief=tk.RIDGE, borderwidth=${w.borderWidth})\n`;
        break;
    }
    code += `        ${varName}.place(x=${Math.round(w.x)}, y=${Math.round(w.y)}, width=${w.width}, height=${w.height})\n\n`;
    
    if (w.type === 'button' || w.eventCode) {
      code += `    def on_${w.name}_click(self):\n`;
      if (w.eventCode) {
        const lines = w.eventCode.split('\n');
        lines.forEach(line => {
          if (!line.trim().startsWith('#')) {
            let convertedLine = line
              .replace(/setWidget\("([^"]+)",\s*"text",\s*"([^"]+)"\)/g, 'self.widgets["$1"]["text"] = "$2"')
              .replace(/setWidget\("([^"]+)",\s*"text",\s*([^\)]+)\)/g, 'self.widgets["$1"]["text"] = $2')
              .replace(/setWidget\("([^"]+)",\s*"value",\s*"([^"]+)"\)/g, 'self.widgets["$1"].delete(0, tk.END); self.widgets["$1"].insert(0, "$2")')
              .replace(/setWidget\("([^"]+)",\s*"value",\s*([^\)]+)\)/g, 'self.widgets["$1"]["value"] = $2')
              .replace(/getWidget\("([^"]+)",\s*"value"\)/g, 'self.widgets["$1"].get()')
              .replace(/msgBox\(/g, 'self.msgBox(');
            code += `        ${convertedLine}\n`;
          }
        });
      } else {
        code += `        print("${w.text} clicked")\n`;
      }
      code += `\n`;
    }
  });

  code += `\nif __name__ == "__main__":\n`;
  code += `    root = tk.Tk()\n`;
  code += `    app = ${formTitle.replace(/\s+/g, '')}(root)\n`;
  code += `    root.mainloop()\n`;
  return code;
};

export const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};


